PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/beb745ef92959db500c8f79ca3518cbf1d67b9b2

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/a96d05c286fc1c619111f220e500b14e18c0509c) in current PX4/master (e2e72fd81e2f02c28a786e9fb5099284d0f3bd3e)
https://github.com/PX4/NuttX/compare/a96d05c286fc1c619111f220e500b14e18c0509c...beb745ef92959db500c8f79ca3518cbf1d67b9b2

beb745ef92 (HEAD, origin/master) sched/pthread: Implement pthread_attr_[get|set]detachstate
f9359d3fe8 boards: stm32f4discovery: Refactor stm32_gs2200m.c
e3b3d21556 boards: cxd56xx: Refactor cxd56_gs2200m.c
83f6c94209 telnet.c: td_offset had been uint8_t. TELNET_RXBUFFER_SIZE over 256 had been broken.
e21dd68755 mmcsd_sdio:Fix breakage from 997d4 SD not functional
1d97b2ecee stack check: Support Stack Smashing Protector(SSP)
f5912b5cba arch: samd5e5 : Oneshot, freerun and tickless available support. All support runs on Timer/Counter (TC). Some fixes in external interrupt controller (EIC) and clockconfig.
171cc38ac2 arch: samd5e5 : Add watchdog timer drivers.
a7a81b5126 libc: Replace all [nx]sem_xxx with _SEM_XXX
8db91a7974 timers/timer.c:397:19: Fix warning: implicit declaration of function 'timer_setcallback'

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/9d80399bd512257d6dc92aba0a520b488423baea

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (e2e72fd81e2f02c28a786e9fb5099284d0f3bd3e)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...9d80399bd512257d6dc92aba0a520b488423baea

9d80399b (HEAD -> master, origin/master) nsh: Accept the command line arguments like sh
78e80908 examples: wget: Fix nxstyle issues
10386cf5 examples/wget: wget example to work without NSH_NETINIT config
7a1d6265 netutils/webclient: Enable to send long HTTP request
18158ed2 system: add libuv port for NuttX
74c506b4 nsh: Don't check CONFIG_NFILE_STREAMS for mkdir/rename/rmdir/fs_unlink
e71e537e ftpc_transfer.c:667:15: Fix error: ‘argc’ undeclared
aaa198f0 interpreters/duktape: Clean objects
08c59984 graphics/lvgl: Specific LVGL version by kconfig
7099bc4b interpreters/duktape: Add console/print/alart support